spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.xiangzi.mybatisplus.dao: debug

mybatis-plus:
  type-aliases-package: com.xiangzi.mybatisplus.model

  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true #驼峰下划线转换
  mapper-locations: com/xiangzi/mybatisplus/mapper/*.xml



